name: Breakage

on:
  workflow_call:
    inputs:
      pkgname:
        required: true
        type: string
      pkgpath:
        required: true
        type: string
      pkgversion:
        required: true
        type: string
      pkgbreak: # "test" or "doc"
        required: false
        default: 'test'
        type: string

jobs:
  break:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v6

      - uses: julia-actions/setup-julia@latest
        with:
          version: 1

      # Cache artifacts (downloads)
      - name: Cache Julia artifacts
        uses: actions/cache@v5
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-breakage-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-breakage-

      - uses: julia-actions/julia-buildpkg@v1

      # --- Breakage test ---
      - name: Run breakage test
        env:
          URL: ${{ inputs.pkgpath }}/${{ inputs.pkgname }}.jl
          VERSION: ${{ inputs.pkgversion }}
          BREAK: ${{ inputs.pkgbreak }}
        run: |
          set -euxo pipefail
          mkdir -p breakage

          PKG_SRC_PATH=$(pwd)
          PKG_SRC_NAME=$(basename "$PKG_SRC_PATH" .jl)

          git clone --depth 1 https://github.com/$URL repo
          cd repo

          # Checkout the version to test
          if [ "$VERSION" = "stable" ]; then
            git fetch --tags || true
            TAG=$(git tag -l "v*" --sort=-creatordate | head -n1 || true)
            if [ -n "$TAG" ]; then
              git checkout "$TAG"
            else
              TAG="no_tag"
            fi
          elif [ "$VERSION" = "latest" ]; then
            TAG="main"
            # Stay on the default branch (already checked out)
          else
            TAG="$VERSION"
            git fetch --tags || true
            if ! git checkout "$TAG" 2>/dev/null; then
              echo "⚠️ Could not checkout $TAG, staying on default branch"
              TAG="default"
            fi
          fi
          export TAG

          PKG_SRC_VERSION=$(julia --project=@. -e '
            using Pkg, Logging;
            with_logger(NullLogger()) do
              Pkg.instantiate()
              try
                version = Pkg.installed()["'"$PKG_SRC_NAME"'"]
                println("compat: v", version)
              catch
                println("")
              end
            end
          ')
          export PKG_SRC_VERSION

          export joburl="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          export outfile="../breakage/breakage-${{ inputs.pkgname }}-${{ inputs.pkgversion }}"

          julia -e '
            using Pkg
            TAG, VERSION, PKG_SRC_VERSION, BREAK, joburl =
              ENV["TAG"], ENV["VERSION"], ENV["PKG_SRC_VERSION"], ENV["BREAK"], ENV["joburl"]

            open(ENV["outfile"], "w") do io
              try
                TAG == "no_tag" && error("No tag for $VERSION")

                if BREAK == "test"
                  pkg"activate ."
                  pkg"instantiate"
                  pkg"status"
                  pkg"dev ../"
                  pkg"build"
                  pkg"test"
                elseif BREAK == "doc"
                  pkg"activate docs"
                  pkg"instantiate"
                  pkg"status"
                  pkg"dev ../"
                  pkg"build"
                  include("docs/make.jl")
                else
                  error("Invalid pkgbreak value: $BREAK")
                end

                print(io, "[![](https://img.shields.io/badge/$BREAK%20$TAG-✅-grey)]($joburl) ", PKG_SRC_VERSION)
              catch e
                @error e
                print(io, "[![](https://img.shields.io/badge/$BREAK%20$TAG-❌-grey)]($joburl) ", PKG_SRC_VERSION)
              end
            end
          '

      - uses: actions/upload-artifact@v6
        with:
          name: breakage-${{ inputs.pkgname }}-${{ inputs.pkgversion }}
          path: breakage/

  comment:
    needs: break
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v7
        with:
          path: breakage/
          pattern: breakage-*
          merge-multiple: true

      - name: Create summary
        run: |
          cd breakage
          {
            echo "Breakage test results"
            echo "Date: $(TZ=UTC date '+%Y-%m-%d %H:%M:%S')"
            echo ""
            echo "| Name | Latest | Stable |"
            echo "|--|--|--|"
            count=0
            for file in breakage-*; do
              [ -f "$file" ] || continue
              if [ "$count" -eq 0 ]; then
                name=$(echo "$file" | cut -d- -f2)
                printf "| %s | " "$name"
              else
                printf "| "
              fi
              cat "$file"
              if [ "$count" -eq 0 ]; then
                printf " "
                count=1
              else
                echo " |"
                count=0
              fi
            done
          } > summary.md

      - name: Comment on PR
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const msg = fs.readFileSync('breakage/summary.md', 'utf8')
            const prNumber = context.payload.pull_request?.number
            if (!prNumber) {
              console.log("No PR number found.")
              return
            }

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            })

            const botComment = comments.find(c => c.user.id === 41898282)
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: msg
              })
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: msg
              })
            }
